/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Caste = { 'sc' : null } |
  { 'st' : null } |
  { 'obc' : null } |
  { 'other' : null } |
  { 'general' : null };
export type Education = { 'phd' : null } |
  { 'highSchool' : null } |
  { 'other' : null } |
  { 'bachelor' : null } |
  { 'master' : null };
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type Profession = { 'doctor' : null } |
  { 'other' : null } |
  { 'teacher' : null } |
  { 'engineer' : null } |
  { 'software' : null } |
  { 'business' : null } |
  { 'artist' : null } |
  { 'government' : null };
export interface Profile {
  'age' : bigint,
  'aboutMe' : string,
  'caste' : Caste,
  'city' : string,
  'name' : string,
  'education' : Education,
  'profession' : Profession,
  'photoUrl' : [] | [string],
  'isProfileComplete' : boolean,
  'state' : string,
  'motherTongue' : string,
  'gender' : Gender,
  'religion' : Religion,
}
export interface ProfileFilter {
  'city' : [] | [string],
  'minAge' : [] | [bigint],
  'maxAge' : [] | [bigint],
  'religion' : [] | [Religion],
}
export type Religion = { 'hindu' : null } |
  { 'other' : null } |
  { 'muslim' : null } |
  { 'sikh' : null } |
  { 'christian' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'browseProfiles' : ActorMethod<[[] | [ProfileFilter]], Array<Profile>>,
  'createOrUpdateProfile' : ActorMethod<[Profile], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOwnProfile' : ActorMethod<[], [] | [Profile]>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProfileComplete' : ActorMethod<[], boolean>,
  'uploadPhoto' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];