/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Religion = IDL.Variant({
  'hindu' : IDL.Null,
  'other' : IDL.Null,
  'muslim' : IDL.Null,
  'sikh' : IDL.Null,
  'christian' : IDL.Null,
});
export const ProfileFilter = IDL.Record({
  'city' : IDL.Opt(IDL.Text),
  'minAge' : IDL.Opt(IDL.Nat),
  'maxAge' : IDL.Opt(IDL.Nat),
  'religion' : IDL.Opt(Religion),
});
export const Caste = IDL.Variant({
  'sc' : IDL.Null,
  'st' : IDL.Null,
  'obc' : IDL.Null,
  'other' : IDL.Null,
  'general' : IDL.Null,
});
export const Education = IDL.Variant({
  'phd' : IDL.Null,
  'highSchool' : IDL.Null,
  'other' : IDL.Null,
  'bachelor' : IDL.Null,
  'master' : IDL.Null,
});
export const Profession = IDL.Variant({
  'doctor' : IDL.Null,
  'other' : IDL.Null,
  'teacher' : IDL.Null,
  'engineer' : IDL.Null,
  'software' : IDL.Null,
  'business' : IDL.Null,
  'artist' : IDL.Null,
  'government' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'aboutMe' : IDL.Text,
  'caste' : Caste,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'education' : Education,
  'profession' : Profession,
  'photoUrl' : IDL.Opt(IDL.Text),
  'isProfileComplete' : IDL.Bool,
  'state' : IDL.Text,
  'motherTongue' : IDL.Text,
  'gender' : Gender,
  'religion' : Religion,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseProfiles' : IDL.Func(
      [IDL.Opt(ProfileFilter)],
      [IDL.Vec(Profile)],
      ['query'],
    ),
  'createOrUpdateProfile' : IDL.Func([Profile], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOwnProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
  'uploadPhoto' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Religion = IDL.Variant({
    'hindu' : IDL.Null,
    'other' : IDL.Null,
    'muslim' : IDL.Null,
    'sikh' : IDL.Null,
    'christian' : IDL.Null,
  });
  const ProfileFilter = IDL.Record({
    'city' : IDL.Opt(IDL.Text),
    'minAge' : IDL.Opt(IDL.Nat),
    'maxAge' : IDL.Opt(IDL.Nat),
    'religion' : IDL.Opt(Religion),
  });
  const Caste = IDL.Variant({
    'sc' : IDL.Null,
    'st' : IDL.Null,
    'obc' : IDL.Null,
    'other' : IDL.Null,
    'general' : IDL.Null,
  });
  const Education = IDL.Variant({
    'phd' : IDL.Null,
    'highSchool' : IDL.Null,
    'other' : IDL.Null,
    'bachelor' : IDL.Null,
    'master' : IDL.Null,
  });
  const Profession = IDL.Variant({
    'doctor' : IDL.Null,
    'other' : IDL.Null,
    'teacher' : IDL.Null,
    'engineer' : IDL.Null,
    'software' : IDL.Null,
    'business' : IDL.Null,
    'artist' : IDL.Null,
    'government' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'aboutMe' : IDL.Text,
    'caste' : Caste,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'education' : Education,
    'profession' : Profession,
    'photoUrl' : IDL.Opt(IDL.Text),
    'isProfileComplete' : IDL.Bool,
    'state' : IDL.Text,
    'motherTongue' : IDL.Text,
    'gender' : Gender,
    'religion' : Religion,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseProfiles' : IDL.Func(
        [IDL.Opt(ProfileFilter)],
        [IDL.Vec(Profile)],
        ['query'],
      ),
    'createOrUpdateProfile' : IDL.Func([Profile], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOwnProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
    'uploadPhoto' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };