/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ProfileFilter {
    city?: string;
    minAge?: bigint;
    maxAge?: bigint;
    religion?: Religion;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Profile {
    age: bigint;
    aboutMe: string;
    caste: Caste;
    city: string;
    name: string;
    education: Education;
    profession: Profession;
    photoUrl?: string;
    isProfileComplete: boolean;
    state: string;
    motherTongue: string;
    gender: Gender;
    religion: Religion;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Caste {
    sc = "sc",
    st = "st",
    obc = "obc",
    other = "other",
    general = "general"
}
export enum Education {
    phd = "phd",
    highSchool = "highSchool",
    other = "other",
    bachelor = "bachelor",
    master = "master"
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum Profession {
    doctor = "doctor",
    other = "other",
    teacher = "teacher",
    engineer = "engineer",
    software = "software",
    business = "business",
    artist = "artist",
    government = "government"
}
export enum Religion {
    hindu = "hindu",
    other = "other",
    muslim = "muslim",
    sikh = "sikh",
    christian = "christian"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    browseProfiles(filter: ProfileFilter | null): Promise<Array<Profile>>;
    createOrUpdateProfile(profile: Profile): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getOwnProfile(): Promise<Profile | null>;
    getProfile(user: Principal): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    isProfileComplete(): Promise<boolean>;
    uploadPhoto(fileName: string): Promise<string>;
}
import type { Caste as _Caste, Education as _Education, Gender as _Gender, Profession as _Profession, Profile as _Profile, ProfileFilter as _ProfileFilter, Religion as _Religion, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async browseProfiles(arg0: ProfileFilter | null): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseProfiles(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseProfiles(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrUpdateProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(to_candid_Profile_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(to_candid_Profile_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnProfile();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnProfile();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isProfileComplete(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isProfileComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isProfileComplete();
            return result;
        }
    }
    async uploadPhoto(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPhoto(arg0);
            return result;
        }
    }
}
function from_candid_Caste_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Caste): Caste {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Education_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Education): Education {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Profession_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profession): Profession {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Religion_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Religion): Religion {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    aboutMe: string;
    caste: _Caste;
    city: string;
    name: string;
    education: _Education;
    profession: _Profession;
    photoUrl: [] | [string];
    isProfileComplete: boolean;
    state: string;
    motherTongue: string;
    gender: _Gender;
    religion: _Religion;
}): {
    age: bigint;
    aboutMe: string;
    caste: Caste;
    city: string;
    name: string;
    education: Education;
    profession: Profession;
    photoUrl?: string;
    isProfileComplete: boolean;
    state: string;
    motherTongue: string;
    gender: Gender;
    religion: Religion;
} {
    return {
        age: value.age,
        aboutMe: value.aboutMe,
        caste: from_candid_Caste_n18(_uploadFile, _downloadFile, value.caste),
        city: value.city,
        name: value.name,
        education: from_candid_Education_n20(_uploadFile, _downloadFile, value.education),
        profession: from_candid_Profession_n22(_uploadFile, _downloadFile, value.profession),
        photoUrl: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.photoUrl)),
        isProfileComplete: value.isProfileComplete,
        state: value.state,
        motherTongue: value.motherTongue,
        gender: from_candid_Gender_n25(_uploadFile, _downloadFile, value.gender),
        religion: from_candid_Religion_n27(_uploadFile, _downloadFile, value.religion)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sc: null;
} | {
    st: null;
} | {
    obc: null;
} | {
    other: null;
} | {
    general: null;
}): Caste {
    return "sc" in value ? Caste.sc : "st" in value ? Caste.st : "obc" in value ? Caste.obc : "other" in value ? Caste.other : "general" in value ? Caste.general : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    phd: null;
} | {
    highSchool: null;
} | {
    other: null;
} | {
    bachelor: null;
} | {
    master: null;
}): Education {
    return "phd" in value ? Education.phd : "highSchool" in value ? Education.highSchool : "other" in value ? Education.other : "bachelor" in value ? Education.bachelor : "master" in value ? Education.master : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doctor: null;
} | {
    other: null;
} | {
    teacher: null;
} | {
    engineer: null;
} | {
    software: null;
} | {
    business: null;
} | {
    artist: null;
} | {
    government: null;
}): Profession {
    return "doctor" in value ? Profession.doctor : "other" in value ? Profession.other : "teacher" in value ? Profession.teacher : "engineer" in value ? Profession.engineer : "software" in value ? Profession.software : "business" in value ? Profession.business : "artist" in value ? Profession.artist : "government" in value ? Profession.government : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindu: null;
} | {
    other: null;
} | {
    muslim: null;
} | {
    sikh: null;
} | {
    christian: null;
}): Religion {
    return "hindu" in value ? Religion.hindu : "other" in value ? Religion.other : "muslim" in value ? Religion.muslim : "sikh" in value ? Religion.sikh : "christian" in value ? Religion.christian : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n16(_uploadFile, _downloadFile, x));
}
function to_candid_Caste_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Caste): _Caste {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_Education_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Education): _Education {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_Profession_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profession): _Profession {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileFilter_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileFilter): _ProfileFilter {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Profile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Religion_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Religion): _Religion {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileFilter | null): [] | [_ProfileFilter] {
    return value === null ? candid_none() : candid_some(to_candid_ProfileFilter_n11(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city?: string;
    minAge?: bigint;
    maxAge?: bigint;
    religion?: Religion;
}): {
    city: [] | [string];
    minAge: [] | [bigint];
    maxAge: [] | [bigint];
    religion: [] | [_Religion];
} {
    return {
        city: value.city ? candid_some(value.city) : candid_none(),
        minAge: value.minAge ? candid_some(value.minAge) : candid_none(),
        maxAge: value.maxAge ? candid_some(value.maxAge) : candid_none(),
        religion: value.religion ? candid_some(to_candid_Religion_n13(_uploadFile, _downloadFile, value.religion)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    aboutMe: string;
    caste: Caste;
    city: string;
    name: string;
    education: Education;
    profession: Profession;
    photoUrl?: string;
    isProfileComplete: boolean;
    state: string;
    motherTongue: string;
    gender: Gender;
    religion: Religion;
}): {
    age: bigint;
    aboutMe: string;
    caste: _Caste;
    city: string;
    name: string;
    education: _Education;
    profession: _Profession;
    photoUrl: [] | [string];
    isProfileComplete: boolean;
    state: string;
    motherTongue: string;
    gender: _Gender;
    religion: _Religion;
} {
    return {
        age: value.age,
        aboutMe: value.aboutMe,
        caste: to_candid_Caste_n31(_uploadFile, _downloadFile, value.caste),
        city: value.city,
        name: value.name,
        education: to_candid_Education_n33(_uploadFile, _downloadFile, value.education),
        profession: to_candid_Profession_n35(_uploadFile, _downloadFile, value.profession),
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        isProfileComplete: value.isProfileComplete,
        state: value.state,
        motherTongue: value.motherTongue,
        gender: to_candid_Gender_n37(_uploadFile, _downloadFile, value.gender),
        religion: to_candid_Religion_n13(_uploadFile, _downloadFile, value.religion)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Religion): {
    hindu: null;
} | {
    other: null;
} | {
    muslim: null;
} | {
    sikh: null;
} | {
    christian: null;
} {
    return value == Religion.hindu ? {
        hindu: null
    } : value == Religion.other ? {
        other: null
    } : value == Religion.muslim ? {
        muslim: null
    } : value == Religion.sikh ? {
        sikh: null
    } : value == Religion.christian ? {
        christian: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Caste): {
    sc: null;
} | {
    st: null;
} | {
    obc: null;
} | {
    other: null;
} | {
    general: null;
} {
    return value == Caste.sc ? {
        sc: null
    } : value == Caste.st ? {
        st: null
    } : value == Caste.obc ? {
        obc: null
    } : value == Caste.other ? {
        other: null
    } : value == Caste.general ? {
        general: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Education): {
    phd: null;
} | {
    highSchool: null;
} | {
    other: null;
} | {
    bachelor: null;
} | {
    master: null;
} {
    return value == Education.phd ? {
        phd: null
    } : value == Education.highSchool ? {
        highSchool: null
    } : value == Education.other ? {
        other: null
    } : value == Education.bachelor ? {
        bachelor: null
    } : value == Education.master ? {
        master: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profession): {
    doctor: null;
} | {
    other: null;
} | {
    teacher: null;
} | {
    engineer: null;
} | {
    software: null;
} | {
    business: null;
} | {
    artist: null;
} | {
    government: null;
} {
    return value == Profession.doctor ? {
        doctor: null
    } : value == Profession.other ? {
        other: null
    } : value == Profession.teacher ? {
        teacher: null
    } : value == Profession.engineer ? {
        engineer: null
    } : value == Profession.software ? {
        software: null
    } : value == Profession.business ? {
        business: null
    } : value == Profession.artist ? {
        artist: null
    } : value == Profession.government ? {
        government: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
